2024-06-29 21:30:35,976 INFO    MainThread:45 [wandb_setup.py:_flush():76] Current SDK version is 0.17.3
2024-06-29 21:30:35,977 INFO    MainThread:45 [wandb_setup.py:_flush():76] Configure stats pid to 45
2024-06-29 21:30:35,977 INFO    MainThread:45 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2024-06-29 21:30:35,978 INFO    MainThread:45 [wandb_setup.py:_flush():76] Loading settings from /working_dir/wandb/settings
2024-06-29 21:30:35,978 INFO    MainThread:45 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'_require_core': 'true'}
2024-06-29 21:30:35,978 INFO    MainThread:45 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-29 21:30:35,978 INFO    MainThread:45 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'src/main.py', 'program_abspath': '/working_dir/src/main.py', 'program': '/working_dir/./src/main.py'}
2024-06-29 21:30:35,978 INFO    MainThread:45 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-29 21:30:35,979 INFO    MainThread:45 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-06-29 21:30:35,979 INFO    MainThread:45 [wandb_init.py:_log_setup():520] Logging user logs to /working_dir/wandb/run-20240629_213035-jaffoh8e/logs/debug.log
2024-06-29 21:30:35,980 INFO    MainThread:45 [wandb_init.py:_log_setup():521] Logging internal logs to /working_dir/wandb/run-20240629_213035-jaffoh8e/logs/debug-internal.log
2024-06-29 21:30:35,980 INFO    MainThread:45 [wandb_init.py:init():560] calling init triggers
2024-06-29 21:30:35,981 INFO    MainThread:45 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'_metadata': ContainerMetadata(ref_type=typing.Any, object_type=<class 'dict'>, optional=True, key=None, flags={'struct': True}, flags_root=False, resolver_cache=defaultdict(<class 'dict'>, {'now': {('%Y-%m-%d',): '2024-06-29', ('%H-%M-%S',): '21-30-14', ('%Y%m%d_%H%M%S',): '20240629_213014'}}), key_type=typing.Any, element_type=typing.Any), '_parent': None, '_flags_cache': {'struct': True, 'convert': None}, '_content': {'network': {'backend': 'pytorch', 'activation': 'SELU', 'initial_weights_regularizer': True, 'initialization': 'Glorot normal', 'iterations': 10, 'LBFGS': False, 'learning_rate': 0.001, 'num_dense_layers': 2, 'num_dense_nodes': 50, 'output_injection_gain': 50, 'resampling': True, 'resampler_period': 100}, 'data': {'L0': 1.0, 'tauf': 1.0, 'k': 1.0, 'p0': 0.0, 'd': 0.03, 'rhoc': 1.0, 'cb': 1.0, 'h': 100.0, 'Tmin': 22, 'Tmax': 30, 'alpha': 1.0, 'W': 0.0, 'steep': 20.0, 'tchange': 0.25}, 'run': 'BioHeat_PINNs_date_time_${now:%Y%m%d_%H%M%S}'}}
2024-06-29 21:30:35,982 INFO    MainThread:45 [wandb_init.py:init():610] starting backend
2024-06-29 21:30:35,982 INFO    MainThread:45 [wandb_init.py:init():614] setting up manager
2024-06-29 21:30:35,994 INFO    MainThread:45 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-06-29 21:30:36,002 INFO    MainThread:45 [wandb_init.py:init():622] backend started and connected
2024-06-29 21:30:36,018 ERROR   MainThread:45 [wandb_init.py:init():1181] error in wandb.init()
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    return wi.init()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 627, in init
    run = Run(
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 594, in __init__
    self._init(
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 715, in _init
    self._config._update(config, ignore_locked=True)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 177, in _update
    sanitized = self._sanitize_dict(
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 264, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 282, in _sanitize
    val = json_friendly_val(val)
  File "/opt/conda/lib/python3.10/site-packages/wandb/util.py", line 674, in json_friendly_val
    converted = asdict(val)
  File "/opt/conda/lib/python3.10/dataclasses.py", line 1238, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/opt/conda/lib/python3.10/dataclasses.py", line 1245, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "/opt/conda/lib/python3.10/dataclasses.py", line 1275, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
TypeError: first argument must be callable or None
2024-06-29 21:30:37,400 WARNING MsgRouterThr:45 [router.py:message_loop():77] message_loop has been closed
